-- 우리 상품(products)과 외부 플랫폼 수집 매물(platform_listings)의 공통 부모 테이블 items 도입.
-- 두 테이블은 각자의 고유 컬럼만 남기고 items(item_id)를 1:1로 참조한다(PK = FK). 공통 컬럼(출처·카테고리·제목·가격·
-- 등록일시)은 items로 옮기고, 둘 중 하나를 가리키던 관심상품/시세 분석/알림의 product_id·listing_id 쌍은 item_id 하나로 합친다.
--
-- ID 규칙: 우리 상품은 기존 product_id를 그대로 item_id로 쓰고(이미지·태그·구성품·외부 게시 등 참조가 많음), 외부 매물만
-- 기존 listing_id + (우리 상품 최대 product_id)로 다시 번호를 매긴다. 이후 새 항목은 items 시퀀스에서 발급한다.

-- 1. 공통 부모 테이블
CREATE TABLE items (
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source      VARCHAR(20)  NOT NULL,
    category_id BIGINT       NOT NULL,
    title       VARCHAR(255) NOT NULL,
    price       BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_items_category FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT ck_items_source CHECK (source IN ('OUR', 'EXTERNAL')),
    CONSTRAINT ck_items_price CHECK (price >= 0)
);

COMMENT ON TABLE items IS '우리 상품과 외부 수집 매물의 공통 부모(출처별 고유 정보는 products/platform_listings에 1:1)';
COMMENT ON COLUMN items.source IS 'OUR=우리 회원 상품(products), EXTERNAL=외부 플랫폼 수집 매물(platform_listings)';

CREATE INDEX idx_items_category_id ON items (category_id);
CREATE INDEX idx_items_created_at ON items (created_at DESC, item_id DESC);

-- 외부 매물 번호 이동 폭(이 마이그레이션 안에서 products.product_id는 바뀌지 않으므로 항상 같은 값)
CREATE TEMPORARY TABLE v20_offset ON COMMIT DROP AS
SELECT COALESCE(MAX(product_id), 0) AS listing_offset FROM products;

INSERT INTO items (item_id, source, category_id, title, price, created_at)
SELECT product_id, 'OUR', category_id, title, price, created_at
FROM products;

INSERT INTO items (item_id, source, category_id, title, price, created_at)
SELECT l.listing_id + o.listing_offset, 'EXTERNAL', l.category_id, l.title, l.price, l.created_at
FROM platform_listings l CROSS JOIN v20_offset o;

SELECT setval(pg_get_serial_sequence('items', 'item_id'), COALESCE((SELECT MAX(item_id) FROM items), 0) + 1, false);

-- 2. 관심상품: product_id/listing_id → item_id
ALTER TABLE interests ADD COLUMN item_id BIGINT;
UPDATE interests i
SET item_id = COALESCE(i.product_id, i.listing_id + o.listing_offset)
FROM v20_offset o;

DROP INDEX uk_interests_member_product;
DROP INDEX uk_interests_member_listing;
ALTER TABLE interests
    DROP CONSTRAINT ck_interests_target_exactly_one,
    DROP CONSTRAINT fk_interests_product,
    DROP CONSTRAINT fk_interests_listing,
    DROP COLUMN product_id,
    DROP COLUMN listing_id,
    ALTER COLUMN item_id SET NOT NULL,
    ADD CONSTRAINT fk_interests_item FOREIGN KEY (item_id) REFERENCES items (item_id),
    ADD CONSTRAINT uk_interests_member_item UNIQUE (member_id, item_id);

CREATE INDEX idx_interests_item_id ON interests (item_id);
COMMENT ON COLUMN interests.item_id IS '관심 대상(우리 상품 또는 외부 매물 — items.source로 구분)';

-- 3. 시세 분석 스냅샷: product_id/listing_id → item_id
ALTER TABLE product_analysis ADD COLUMN item_id BIGINT;
UPDATE product_analysis pa
SET item_id = COALESCE(pa.product_id, pa.listing_id + o.listing_offset)
FROM v20_offset o;

DROP INDEX idx_product_analysis_product_id_analyzed_at;
DROP INDEX idx_product_analysis_listing_id_analyzed_at;
ALTER TABLE product_analysis
    DROP CONSTRAINT ck_product_analysis_target_exactly_one,
    DROP CONSTRAINT fk_product_analysis_product,
    DROP CONSTRAINT fk_product_analysis_listing,
    DROP COLUMN product_id,
    DROP COLUMN listing_id,
    ALTER COLUMN item_id SET NOT NULL,
    ADD CONSTRAINT fk_product_analysis_item FOREIGN KEY (item_id) REFERENCES items (item_id);

CREATE INDEX idx_product_analysis_item_id_analyzed_at ON product_analysis (item_id, analyzed_at DESC);
COMMENT ON COLUMN product_analysis.item_id IS '분석 대상(우리 상품 또는 관심 등록된 외부 매물)';

-- 4. 알림: product_id/listing_id → item_id(공지성 알림 등 대상이 없으면 NULL)
ALTER TABLE notifications ADD COLUMN item_id BIGINT;
UPDATE notifications n
SET item_id = COALESCE(n.product_id, n.listing_id + o.listing_offset)
FROM v20_offset o;

ALTER TABLE notifications
    DROP CONSTRAINT ck_notifications_target_at_most_one,
    DROP CONSTRAINT fk_notifications_product,
    DROP CONSTRAINT fk_notifications_listing,
    DROP COLUMN product_id,
    DROP COLUMN listing_id,
    ADD CONSTRAINT fk_notifications_item FOREIGN KEY (item_id) REFERENCES items (item_id);

COMMENT ON COLUMN notifications.item_id IS '알림 대상(우리 상품 또는 외부 매물), 상품과 무관한 알림이면 NULL';

-- 5. 외부 매물: 번호 이동 후 공통 컬럼 제거, items 참조
ALTER TABLE platform_listings ALTER COLUMN listing_id DROP IDENTITY;
-- PK 유일성은 행마다 즉시 검사돼 한 번에 +offset 하면 아직 옮기지 않은 행과 겹친다 → 음수로 한 번 거쳐 옮긴다.
UPDATE platform_listings l
SET listing_id = -(l.listing_id + o.listing_offset)
FROM v20_offset o;
UPDATE platform_listings SET listing_id = -listing_id;

ALTER TABLE platform_listings
    DROP CONSTRAINT ck_platform_listings_price,
    DROP CONSTRAINT fk_platform_listings_category,
    DROP COLUMN category_id,
    DROP COLUMN title,
    DROP COLUMN price,
    DROP COLUMN created_at,
    ADD CONSTRAINT fk_platform_listings_item FOREIGN KEY (listing_id) REFERENCES items (item_id);

COMMENT ON COLUMN platform_listings.listing_id IS 'items.item_id와 같은 값(PK = FK)';

-- 6. 우리 상품: 공통 컬럼 제거, items 참조(product_id 값은 그대로)
ALTER TABLE products ALTER COLUMN product_id DROP IDENTITY;
ALTER TABLE products
    DROP CONSTRAINT ck_products_price,
    DROP CONSTRAINT fk_products_category,
    DROP COLUMN category_id,
    DROP COLUMN title,
    DROP COLUMN price,
    DROP COLUMN created_at,
    ADD CONSTRAINT fk_products_item FOREIGN KEY (product_id) REFERENCES items (item_id);

COMMENT ON COLUMN products.product_id IS 'items.item_id와 같은 값(PK = FK)';
