-- notification_type ENUM에 PLATFORM_EXPIRED(외부 플랫폼 연동 세션 만료 알림) 추가 (SELL/HOLD/BUY/WAIT/NOTICE/TARGET_PRICE/PLATFORM_EXPIRED)
ALTER TYPE notification_type ADD VALUE 'PLATFORM_EXPIRED';

COMMENT ON TYPE notification_type IS '알림 유형 (SELL, HOLD, BUY, WAIT, NOTICE, TARGET_PRICE, PLATFORM_EXPIRED)';
