ALTER TABLE products DROP COLUMN purchased_at;

-- 대분류 카테고리입니다
INSERT INTO categories (name) VALUES
    ('여성의류'),
    ('남성의류'),
    ('신발'),
    ('가방/지갑'),
    ('시계'),
    ('주얼리'),
    ('패션잡화'),
    ('뷰티/미용'),
    ('디지털'),
    ('가전제품'),
    ('스포츠/레저'),
    ('스타굿즈'),
    ('키덜트'),
    ('트레이딩카드'),
    ('음반/악기'),
    ('도서/티켓/문구'),
    ('예술/희귀/수집품'),
    ('가구/인테리어'),
    ('생활/주방용품'),
    ('공구/산업용품'),
    ('식품'),
    ('유아동/출산'),
    ('반려동물용품'),
    ('재능'),
    ('기타');

-- 중분류 카테고리입니다
INSERT INTO categories (name, parent_id) VALUES
    ('여성 아우터', (SELECT category_id FROM categories WHERE name = '여성의류')),
    ('여성 상의', (SELECT category_id FROM categories WHERE name = '여성의류')),
    ('여성 하의', (SELECT category_id FROM categories WHERE name = '여성의류')),
    ('원피스', (SELECT category_id FROM categories WHERE name = '여성의류')),
    ('여성 이너웨어/홈웨어', (SELECT category_id FROM categories WHERE name = '여성의류')),
    ('남성 아우터', (SELECT category_id FROM categories WHERE name = '남성의류')),
    ('남성 상의', (SELECT category_id FROM categories WHERE name = '남성의류')),
    ('남성 하의', (SELECT category_id FROM categories WHERE name = '남성의류')),
    ('남성 이너웨어/홈웨어', (SELECT category_id FROM categories WHERE name = '남성의류')),
    ('스니커즈', (SELECT category_id FROM categories WHERE name = '신발')),
    ('구두/로퍼', (SELECT category_id FROM categories WHERE name = '신발')),
    ('부츠', (SELECT category_id FROM categories WHERE name = '신발')),
    ('샌들/슬리퍼', (SELECT category_id FROM categories WHERE name = '신발')),
    ('스포츠화', (SELECT category_id FROM categories WHERE name = '신발')),
    ('백팩', (SELECT category_id FROM categories WHERE name = '가방/지갑')),
    ('크로스백/숄더백', (SELECT category_id FROM categories WHERE name = '가방/지갑')),
    ('토트백', (SELECT category_id FROM categories WHERE name = '가방/지갑')),
    ('지갑', (SELECT category_id FROM categories WHERE name = '가방/지갑')),
    ('여행가방/캐리어', (SELECT category_id FROM categories WHERE name = '가방/지갑')),
    ('남성시계', (SELECT category_id FROM categories WHERE name = '시계')),
    ('여성시계', (SELECT category_id FROM categories WHERE name = '시계')),
    ('커플시계', (SELECT category_id FROM categories WHERE name = '시계')),
    ('목걸이', (SELECT category_id FROM categories WHERE name = '주얼리')),
    ('반지', (SELECT category_id FROM categories WHERE name = '주얼리')),
    ('귀걸이/피어싱', (SELECT category_id FROM categories WHERE name = '주얼리')),
    ('팔찌', (SELECT category_id FROM categories WHERE name = '주얼리')),
    ('벨트', (SELECT category_id FROM categories WHERE name = '패션잡화')),
    ('모자', (SELECT category_id FROM categories WHERE name = '패션잡화')),
    ('스카프/머플러', (SELECT category_id FROM categories WHERE name = '패션잡화')),
    ('선글라스/안경', (SELECT category_id FROM categories WHERE name = '패션잡화')),
    ('장갑', (SELECT category_id FROM categories WHERE name = '패션잡화')),
    ('스킨케어', (SELECT category_id FROM categories WHERE name = '뷰티/미용')),
    ('메이크업', (SELECT category_id FROM categories WHERE name = '뷰티/미용')),
    ('향수', (SELECT category_id FROM categories WHERE name = '뷰티/미용')),
    ('헤어/바디케어', (SELECT category_id FROM categories WHERE name = '뷰티/미용')),
    ('미용기기', (SELECT category_id FROM categories WHERE name = '뷰티/미용')),
    ('스마트폰', (SELECT category_id FROM categories WHERE name = '디지털')),
    ('노트북/PC', (SELECT category_id FROM categories WHERE name = '디지털')),
    ('태블릿', (SELECT category_id FROM categories WHERE name = '디지털')),
    ('카메라/캠코더', (SELECT category_id FROM categories WHERE name = '디지털')),
    ('오디오', (SELECT category_id FROM categories WHERE name = '디지털')),
    ('웨어러블', (SELECT category_id FROM categories WHERE name = '디지털')),
    ('게임/콘솔', (SELECT category_id FROM categories WHERE name = '디지털')),
    ('TV/영상가전', (SELECT category_id FROM categories WHERE name = '가전제품')),
    ('생활가전', (SELECT category_id FROM categories WHERE name = '가전제품')),
    ('주방가전', (SELECT category_id FROM categories WHERE name = '가전제품')),
    ('스마트홈/네트워크기기', (SELECT category_id FROM categories WHERE name = '가전제품')),
    ('계절가전', (SELECT category_id FROM categories WHERE name = '가전제품')),
    ('헬스/피트니스', (SELECT category_id FROM categories WHERE name = '스포츠/레저')),
    ('골프', (SELECT category_id FROM categories WHERE name = '스포츠/레저')),
    ('자전거', (SELECT category_id FROM categories WHERE name = '스포츠/레저')),
    ('캠핑/등산', (SELECT category_id FROM categories WHERE name = '스포츠/레저')),
    ('구기종목', (SELECT category_id FROM categories WHERE name = '스포츠/레저')),
    ('수상/레저스포츠', (SELECT category_id FROM categories WHERE name = '스포츠/레저')),
    ('앨범/포토카드', (SELECT category_id FROM categories WHERE name = '스타굿즈')),
    ('응원봉/굿즈', (SELECT category_id FROM categories WHERE name = '스타굿즈')),
    ('슬로건/포스터', (SELECT category_id FROM categories WHERE name = '스타굿즈')),
    ('피규어', (SELECT category_id FROM categories WHERE name = '키덜트')),
    ('프라모델', (SELECT category_id FROM categories WHERE name = '키덜트')),
    ('레고/블록완구', (SELECT category_id FROM categories WHERE name = '키덜트')),
    ('RC카/RC용품', (SELECT category_id FROM categories WHERE name = '키덜트')),
    ('포켓몬카드', (SELECT category_id FROM categories WHERE name = '트레이딩카드')),
    ('스포츠카드', (SELECT category_id FROM categories WHERE name = '트레이딩카드')),
    ('TCG(유희왕·매직)', (SELECT category_id FROM categories WHERE name = '트레이딩카드')),
    ('음반(LP/CD)', (SELECT category_id FROM categories WHERE name = '음반/악기')),
    ('기타(악기)', (SELECT category_id FROM categories WHERE name = '음반/악기')),
    ('건반악기', (SELECT category_id FROM categories WHERE name = '음반/악기')),
    ('관악기/타악기', (SELECT category_id FROM categories WHERE name = '음반/악기')),
    ('음향장비', (SELECT category_id FROM categories WHERE name = '음반/악기')),
    ('도서', (SELECT category_id FROM categories WHERE name = '도서/티켓/문구')),
    ('티켓/교환권', (SELECT category_id FROM categories WHERE name = '도서/티켓/문구')),
    ('문구/팬시', (SELECT category_id FROM categories WHERE name = '도서/티켓/문구')),
    ('다이어리/노트', (SELECT category_id FROM categories WHERE name = '도서/티켓/문구')),
    ('그림/판화', (SELECT category_id FROM categories WHERE name = '예술/희귀/수집품')),
    ('조각/공예품', (SELECT category_id FROM categories WHERE name = '예술/희귀/수집품')),
    ('골동품', (SELECT category_id FROM categories WHERE name = '예술/희귀/수집품')),
    ('화폐/우표', (SELECT category_id FROM categories WHERE name = '예술/희귀/수집품')),
    ('침실가구', (SELECT category_id FROM categories WHERE name = '가구/인테리어')),
    ('거실가구', (SELECT category_id FROM categories WHERE name = '가구/인테리어')),
    ('수납가구', (SELECT category_id FROM categories WHERE name = '가구/인테리어')),
    ('조명', (SELECT category_id FROM categories WHERE name = '가구/인테리어')),
    ('인테리어소품', (SELECT category_id FROM categories WHERE name = '가구/인테리어')),
    ('주방용품', (SELECT category_id FROM categories WHERE name = '생활/주방용품')),
    ('욕실용품', (SELECT category_id FROM categories WHERE name = '생활/주방용품')),
    ('수납/정리용품', (SELECT category_id FROM categories WHERE name = '생활/주방용품')),
    ('침구/커튼', (SELECT category_id FROM categories WHERE name = '생활/주방용품')),
    ('전동공구', (SELECT category_id FROM categories WHERE name = '공구/산업용품')),
    ('수공구', (SELECT category_id FROM categories WHERE name = '공구/산업용품')),
    ('농기구/원예용품', (SELECT category_id FROM categories WHERE name = '공구/산업용품')),
    ('안전용품', (SELECT category_id FROM categories WHERE name = '공구/산업용품')),
    ('건강기능식품', (SELECT category_id FROM categories WHERE name = '식품')),
    ('가공식품', (SELECT category_id FROM categories WHERE name = '식품')),
    ('신선/농수산물', (SELECT category_id FROM categories WHERE name = '식품')),
    ('유아동의류', (SELECT category_id FROM categories WHERE name = '유아동/출산')),
    ('유아용품', (SELECT category_id FROM categories WHERE name = '유아동/출산')),
    ('유모차/카시트', (SELECT category_id FROM categories WHERE name = '유아동/출산')),
    ('장난감/완구', (SELECT category_id FROM categories WHERE name = '유아동/출산')),
    ('유아도서/교구', (SELECT category_id FROM categories WHERE name = '유아동/출산')),
    ('사료/간식', (SELECT category_id FROM categories WHERE name = '반려동물용품')),
    ('하우스/케이지', (SELECT category_id FROM categories WHERE name = '반려동물용품')),
    ('반려동물장난감/미용용품', (SELECT category_id FROM categories WHERE name = '반려동물용품')),
    ('반려동물의류/악세서리', (SELECT category_id FROM categories WHERE name = '반려동물용품')),
    ('과외/교육', (SELECT category_id FROM categories WHERE name = '재능')),
    ('디자인/제작', (SELECT category_id FROM categories WHERE name = '재능')),
    ('사진/영상', (SELECT category_id FROM categories WHERE name = '재능')),
    ('기타 재능', (SELECT category_id FROM categories WHERE name = '재능'));

-- 소분류 카테고리입니다
INSERT INTO categories (name, parent_id) VALUES
    ('헤어기기', (SELECT category_id FROM categories WHERE name = '미용기기')),
    ('피부미용기기', (SELECT category_id FROM categories WHERE name = '미용기기')),
    ('아이폰', (SELECT category_id FROM categories WHERE name = '스마트폰')),
    ('갤럭시', (SELECT category_id FROM categories WHERE name = '스마트폰')),
    ('기타 스마트폰', (SELECT category_id FROM categories WHERE name = '스마트폰')),
    ('노트북', (SELECT category_id FROM categories WHERE name = '노트북/PC')),
    ('데스크탑', (SELECT category_id FROM categories WHERE name = '노트북/PC')),
    ('모니터', (SELECT category_id FROM categories WHERE name = '노트북/PC')),
    ('PC 주변기기', (SELECT category_id FROM categories WHERE name = '노트북/PC')),
    ('아이패드', (SELECT category_id FROM categories WHERE name = '태블릿')),
    ('갤럭시탭', (SELECT category_id FROM categories WHERE name = '태블릿')),
    ('기타 태블릿', (SELECT category_id FROM categories WHERE name = '태블릿')),
    ('디지털카메라', (SELECT category_id FROM categories WHERE name = '카메라/캠코더')),
    ('미러리스/DSLR', (SELECT category_id FROM categories WHERE name = '카메라/캠코더')),
    ('드론/짐벌', (SELECT category_id FROM categories WHERE name = '카메라/캠코더')),
    ('렌즈·카메라용품', (SELECT category_id FROM categories WHERE name = '카메라/캠코더')),
    ('이어폰/헤드폰', (SELECT category_id FROM categories WHERE name = '오디오')),
    ('블루투스 스피커', (SELECT category_id FROM categories WHERE name = '오디오')),
    ('마이크/음향장비', (SELECT category_id FROM categories WHERE name = '오디오')),
    ('애플워치', (SELECT category_id FROM categories WHERE name = '웨어러블')),
    ('갤럭시워치', (SELECT category_id FROM categories WHERE name = '웨어러블')),
    ('기타 웨어러블', (SELECT category_id FROM categories WHERE name = '웨어러블')),
    ('콘솔', (SELECT category_id FROM categories WHERE name = '게임/콘솔')),
    ('게임 타이틀', (SELECT category_id FROM categories WHERE name = '게임/콘솔')),
    ('VR기기', (SELECT category_id FROM categories WHERE name = '게임/콘솔')),
    ('게임 주변기기', (SELECT category_id FROM categories WHERE name = '게임/콘솔')),
    ('TV', (SELECT category_id FROM categories WHERE name = 'TV/영상가전')),
    ('프로젝터', (SELECT category_id FROM categories WHERE name = 'TV/영상가전')),
    ('셋톱박스', (SELECT category_id FROM categories WHERE name = 'TV/영상가전')),
    ('청소기', (SELECT category_id FROM categories WHERE name = '생활가전')),
    ('공기청정기', (SELECT category_id FROM categories WHERE name = '생활가전')),
    ('세탁기/건조기', (SELECT category_id FROM categories WHERE name = '생활가전')),
    ('냉장고', (SELECT category_id FROM categories WHERE name = '생활가전')),
    ('전자레인지', (SELECT category_id FROM categories WHERE name = '주방가전')),
    ('커피머신', (SELECT category_id FROM categories WHERE name = '주방가전')),
    ('에어프라이어', (SELECT category_id FROM categories WHERE name = '주방가전')),
    ('스마트스피커/CCTV', (SELECT category_id FROM categories WHERE name = '스마트홈/네트워크기기')),
    ('공유기/네트워크장비', (SELECT category_id FROM categories WHERE name = '스마트홈/네트워크기기')),
    ('에어컨', (SELECT category_id FROM categories WHERE name = '계절가전')),
    ('선풍기', (SELECT category_id FROM categories WHERE name = '계절가전')),
    ('히터', (SELECT category_id FROM categories WHERE name = '계절가전')),
    ('침대', (SELECT category_id FROM categories WHERE name = '침실가구')),
    ('매트리스', (SELECT category_id FROM categories WHERE name = '침실가구')),
    ('소파', (SELECT category_id FROM categories WHERE name = '거실가구')),
    ('테이블', (SELECT category_id FROM categories WHERE name = '거실가구')),
    ('옷장', (SELECT category_id FROM categories WHERE name = '수납가구')),
    ('서랍장', (SELECT category_id FROM categories WHERE name = '수납가구')),
    ('식기', (SELECT category_id FROM categories WHERE name = '주방용품')),
    ('조리도구', (SELECT category_id FROM categories WHERE name = '주방용품')),
    ('기저귀', (SELECT category_id FROM categories WHERE name = '유아용품')),
    ('젖병', (SELECT category_id FROM categories WHERE name = '유아용품'));
