# ==========================================
# 공통
# ==========================================
spring:
  profiles:
    active: local

# JPA 공통 설정
  jpa:
    open-in-view: false # DB 커넥션 고갈 방지
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # IN절 한 번에 가져오는 개수
        jdbc:
          time_zone: Asia/Seoul

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000       # 1시간
  refresh-token-expiration: 1209600000   # 14일

# 스웨거 설정
springdoc:
  swagger-ui:
    path: /swagger
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /docs
