# ==========================================
# 개발 서버
# ==========================================
spring:
# 데이터베이스 설정
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        highlight_sql: true

# JWT 설정
jwt:
  secret: ${JWT_ACCESS_SECRET_KEY}
  refresh-secret: ${JWT_REFRESH_SECRET_KEY}

# 개발 로깅 설정
logging:
  level:
    com.swyp.team5: debug
    org.hibernate.SQL: info # SQL 로그가 많아 꺼 둠(필요할 때만 debug)
    org.hibernate.orm.jdbc.bind: info # 바인딩 값(개인정보 포함 가능) 로그 꺼 둠(필요할 때만 trace)

# 스프링 엑츄에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  endpoint:
    health:
      show-details: always
